FROM mcr.microsoft.com/mssql-tools

LABEL org.opencontainers.image.title="Qubdi SyncDB MSSQL Tools"
LABEL org.opencontainers.image.description="SQL Server tools image for Qubdi SyncDB MSSQL seed initialization"
