FROM mcr.microsoft.com/mssql/server:2022-CU23-ubuntu-22.04

LABEL org.opencontainers.image.title="Qubdi SyncDB MSSQL Tools"
LABEL org.opencontainers.image.description="SQL Server tools image for Qubdi SyncDB MSSQL seed initialization"
