FROM mcr.microsoft.com/mssql/server:2022-latest

LABEL org.opencontainers.image.title="Qubdi SyncDB MSSQL Test Database"
LABEL org.opencontainers.image.description="Microsoft SQL Server test image for Qubdi SyncDB integration tests"
