FROM mcr.microsoft.com/mssql/server:2022-CU23-ubuntu-22.04

LABEL org.opencontainers.image.title="Qubdi SyncDB MSSQL Test Database"
LABEL org.opencontainers.image.description="Microsoft SQL Server test image for Qubdi SyncDB integration tests"
